---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
#setwd("~/R/projects/STAT510-F22")
```

```{r}
Access.Points <- read_fwf("../raw_data/accessPointLocations.txt", skip = 1) # Read access point locations as a fixed width file
colnames(Access.Points) <- c("MAC", "AP.pos.x", "AP.pos.y") # Set column names
Access.Points
```



```{r}
# Read in each line and replace all delimiters to commas
read_lines("../raw_data/offline.final.trace.txt") %>% 
  str_replace_all("[=;]", ",") -> data_raw

# Each observation has a variable number of connected access points; determine the maximum.
str_count(data_raw, pattern = ",") + 1 -> num_column
(max(num_column) - 10) / 4 -> num_res

# Generate column names based on number of observations
# "drop" columns are remaining from the equals sign delimiter;
# they will be dropped as part of the data cleanup.
paste("Response", 1:num_res, sep = "") %>% 
  outer(c(".MAC", ".SignalStrengthValue", ".Frequency", ".Mode"), paste0) %>% 
  t() %>% as.vector() -> column_names
c(
  "drop.t", "Timestamp", "drop.id", "MACofScanDevice",
  "drop.pos", "Scan.pos.x", "Scan.pos.y", "Scan.pos.z",
  "drop.degree", "orientation", column_names
) -> column_names

# Add column names to the start of the "file" we read in from data_raw
# This will _force_ the correct number of columns, even though the parser will
#   still throw a warning.
column_names %>% paste0(collapse = ",") %>% 
  c(data_raw) %>% 
  paste0(collapse = "\n") %>% 
  read_csv(comment = "#", show_col_types = FALSE) -> data
```

```{r}
# Helper functions
dist <- function(x1, x2, y1, y2) {
  # Get distance between (x1, y1) and (x2, y2)
  sqrt((x1 - x2)^2 + (y1 - y2)^2)
}

cast <- function(x1, x2, y1, y2, angle) {
  # Get angle between device orientation and access point
  # Unused
  r <- angle * pi / 180
  h <- c(-cos(r), sin(r))
  v <- c(x2 - x1, y2 - y1) / dist(x1, x2, y1, y2)
  acos(sum(h * v)) * 180 / pi
}

vcast <- Vectorize(cast)

# Data cleaning first pass
data %>%
  select(!starts_with("drop")) %>%                                              # Drop = delimiter columns
  pivot_longer(cols = starts_with("Response"),                                  # Pivot Response<> to a tall format
               names_to = c("Response", ".value"),
               names_pattern = "^Response(\\d+)\\.(.*)") %>% 
  filter(Mode == 3) %>%                                                         # Only include access points in mode 3
  mutate(
    Timestamp = as_datetime(Timestamp/1000),                                    # Convert timestamp (ms) to datetime object
    orientation.r = (45 * round(orientation / 45)) %% 360                       # Round orientation to nearest 45 degree increment
  ) %>%
  right_join(Access.Points) %>%                                                 # Use right_join to filter down only to the access points of interest
  mutate(
    distance = dist(Scan.pos.x, AP.pos.x, Scan.pos.y, AP.pos.y),                # Get distance from scan device to access point
  ) %>%
  group_by(Scan.pos.x, Scan.pos.y, orientation) %>%
  mutate(Timestamp.init = min(Timestamp)) %>%                                   # For each position and orientation, record the starting timestamp
  select(                                                                       # Reorder
    Timestamp.init, Timestamp, MACofScanDevice,
    Scan.pos.x, Scan.pos.y, Scan.pos.z, orientation, orientation.r, Response,
    MAC, SignalStrengthValue, Frequency, Mode, AP.pos.x, AP.pos.y, distance
  ) -> test_data
```

```{r}
test_data %>%
  filter(Timestamp.init == unique(test_data$Timestamp.init)[9]) %>%
  ggplot(
    aes(x = Timestamp, y = SignalStrengthValue, color = MAC, group = MAC)
  ) + 
  geom_line()
```


```{r}
test_data %>%
  mutate(                                                                       # half-Hampel Filter
    lb = median(SignalStrengthValue) - 3 * mad(SignalStrengthValue, constant = 1),
    ub = median(SignalStrengthValue) + 3 * mad(SignalStrengthValue, constant = 1)
  ) %>%
  group_by(Scan.pos.x, Scan.pos.y, orientation.r, MAC) %>%
  filter(SignalStrengthValue >= lb) %>%
  ungroup()-> test_data

test_data %>%
  filter(Timestamp.init == unique(test_data$Timestamp.init)[9]) %>%
  ggplot(
    aes(x = Timestamp, y = SignalStrengthValue, color = MAC, group = MAC)
  ) + 
  geom_line()
```



```{r}
test_data %>%
  # Generate median and sd signal strength variables
  group_by(Scan.pos.x, Scan.pos.y, orientation.r, MAC, distance, AP.pos.x, AP.pos.y) %>%
  summarize(median.Signal = median(SignalStrengthValue),
            sd.Signal = sd(SignalStrengthValue)) %>%
  ungroup() -> test_data.m
```




```{r}
test_data.m %>%
  ggplot(aes(x = median.Signal, y = distance, color = MAC)) + 
  geom_point() + 
  facet_wrap(.~MAC) + 
  theme(legend.position = "None")
```

```{r}
test_data %>%
  # Test if orientation is statistically significant
  filter(MAC == "00:14:bf:b1:97:81") %>%
  filter(distance == min(distance)) %>%
  aov(SignalStrengthValue ~ orientation.r, data = .) %>% summary()

test_data %>%
  filter(MAC == "00:14:bf:b1:97:90") %>%
  filter(distance == min(distance)) %>%
  ggplot(aes(x = SignalStrengthValue, y = orientation.r, group = orientation.r)) +
  geom_boxplot()
```


```{r}
MAC.names <- unique(test_data.m$MAC)
# For each mac address, generate a linear model
lapply(MAC.names, function(x) {
  test_data.m %>%
    filter(MAC == x) %>%
    lm(formula = distance ~ median.Signal, data = .)
}) %>%
  `names<-`(MAC.names) -> fit

# Generate summary statistics for each model separately and together
lapply(fit, summary)
summary(lm(formula = distance ~ median.Signal, data = test_data.m))
```


```{r}
# Read in each line and replace all delimiters to commas
read_lines("../raw_data/online.final.trace.txt") %>% 
  str_replace_all("[=;]", ",") -> data_raw.t

# Each observation has a variable number of connected access points; determine the maximum.
str_count(data_raw.t, pattern = ",") + 1 -> num_column
(max(num_column) - 10) / 4 -> num_res

# Generate column names based on number of observations
# "drop" columns are remaining from the equals sign delimiter;
# they will be dropped as part of the data cleanup.
paste("Response", 1:num_res, sep = "") %>% 
  outer(c(".MAC", ".SignalStrengthValue", ".Frequency", ".Mode"), paste0) %>% 
  t() %>% as.vector() -> column_names
c(
  "drop.t", "Timestamp", "drop.id", "MACofScanDevice",
  "drop.pos", "Scan.pos.x", "Scan.pos.y", "Scan.pos.z",
  "drop.degree", "orientation", column_names
) -> column_names

# Add column names to the start of the "file" we read in from data_raw
# This will _force_ the correct number of columns, even though the parser will
#   still throw a warning.
column_names %>% paste0(collapse = ",") %>% 
  c(data_raw.t) %>% 
  paste0(collapse = "\n") %>% 
  read_csv(comment = "#", show_col_types = FALSE) -> data.t
```

```{r}
data.t %>%
  select(!starts_with("drop")) %>%                                              # Drop = delimiter columns
  pivot_longer(cols = starts_with("Response"),                                  # Pivot Response<> to a tall format
               names_to = c("Response", ".value"),
               names_pattern = "^Response(\\d+)\\.(.*)") %>% 
  filter(Mode == 3) %>%                                                         # Only include access points in mode 3
  mutate(
    Timestamp = as_datetime(Timestamp/1000),                                    # Convert timestamp (ms) to datetime object
    orientation.r = (45 * round(orientation / 45)) %% 360                       # Round orientation to nearest 45 degree increment
  ) %>%
  right_join(Access.Points) %>%                                                 # Use right_join to filter down only to the access points of interest
  mutate(
    distance = dist(Scan.pos.x, AP.pos.x, Scan.pos.y, AP.pos.y),                # Get distance from scan device to access point
  ) %>%
  group_by(Scan.pos.x, Scan.pos.y, orientation) %>%
  mutate(Timestamp.init = min(Timestamp)) %>%                                   # For each position and orientation, record the starting timestamp
  group_by(Scan.pos.x, Scan.pos.y, orientation.r, MAC) %>%
  mutate(                                                                       # half-Hampel Filter
    lb = median(SignalStrengthValue) - 3 * mad(SignalStrengthValue, constant = 1),
    ub = median(SignalStrengthValue) + 3 * mad(SignalStrengthValue, constant = 1)
  ) %>%
  filter(SignalStrengthValue >= lb) %>%
  ungroup() %>% 
  select(                                                                       # Reorder
    Timestamp.init, Timestamp, MACofScanDevice,
    Scan.pos.x, Scan.pos.y, Scan.pos.z, orientation, orientation.r, Response,
    MAC, SignalStrengthValue, Frequency, Mode, AP.pos.x, AP.pos.y, distance
  ) -> test_data

test_data %>%
  group_by(Scan.pos.x, Scan.pos.y, orientation.r, MAC, distance, AP.pos.x, AP.pos.y) %>%
  summarize(median.Signal = median(SignalStrengthValue),
            sd.Signal = sd(SignalStrengthValue)) %>%
  ungroup() -> test_data.m.t
```

```{r}
lapply(MAC.names, function(x) {
  # For each MAC address, generate predicted distances
  test_data.m.t %>%
    filter(MAC == x) %>%
    mutate(pred_dist = predict(fit[[x]], cur_data()))
}) %>%
  do.call(rbind, .) -> test_data.m.t.pred
```



```{r}
opt_dist <- function(data, pos.x, pos.y) {
  # data contains relevant access points and distance to those access points
  # Determine the distance between test point and access points,
  # and measure the square distance error
  n <- dim(data)[1]
  cbind(data, X = rep(pos.x, n), Y = rep(pos.y, n)) %>%
    mutate(err = (dist(pos.x, AP.pos.x, pos.y, AP.pos.y) - pred_dist)^2) %>%
    summarise(err = sum(err)) %>% unlist
}

# Initial point is at mean of all AP locations
init.point <- c(mean(Access.Points$AP.pos.x), mean(Access.Points$AP.pos.y))

#optim(
#  par = init.point,
#  fn = \(x){opt_dist(data = filter(test_data.m.t, Scan.pos.x == 0, Scan.pos.y == 0, orientation.r == 0), x[1], x[2])}
#)$par
```

```{r}
# Generate unique list of each position and orientation
test_data.m.t.pred %>%
  select(Scan.pos.x, Scan.pos.y, orientation.r) %>%
  unique -> test_data.m.names


test_data.m.names %>%
  as.matrix %>%
  apply(1, function(x){
    # For each position / orientation, minimize error distance with opt_dist
    filter(test_data.m.t.pred, Scan.pos.x == x[1], Scan.pos.y == x[2], orientation.r == x[3]) %>%
      #filter(median.Signal <= median(median.Signal)) %>%
      optim(
        par = init.point, 
        fn = \(y){opt_dist(data = ., y[1], y[2])}
      ) %>%
      `$`(par)
  }) %>%
  t() -> test_data.m.t.res
```


```{r}
# Distances between predicted and actual locations
(cbind(test_data.m.names, test_data.m.t.res) %>%
  mutate(err = dist(Scan.pos.x, `1`, Scan.pos.y, `2`))) %>%
  rename("Scan.pos.x.pred" = `1`, Scan.pos.y.pred = `2`) -> test_data.final
test_data.final
```



General Visualizations below this point


```{r}
floorErrorMap <- function(estXY, actualXY, trainPoints = NULL, AP = NULL){
  
  plot(0, 0, xlim = c(0, 35), ylim = c(-3, 15), type = "n",
       xlab = "", ylab = "", axes = FALSE)
  box()
  if ( !is.null(AP) ) points(AP, pch = 15)
  if ( !is.null(trainPoints) )
    points(trainPoints, pch = 19, col="grey", cex = 0.6)
  
  points(x = actualXY[, 1], y = actualXY[, 2], 
         pch = 19, cex = 0.8 )
  points(x = estXY[, 1], y = estXY[, 2], 
         pch = 4, col="red", cex = 0.8 )
  segments(x0 = estXY[, 1], y0 = estXY[, 2],
           x1 = actualXY[, 1], y1 = actualXY[ , 2],
           lwd = 2, col = "grey")
  segments(7.8, 2.3, 7.8, -3.4,
           lwd = 1, col = "black")
  segments(11.3,2.3, 11.3,-3.4, 
           lwd = 1, col = "black")
  segments(16.1,2.3, 16.1,-3.4,
           lwd = 1, col = "black")
  segments(19.8,2.3, 19.8,-3.4,
           lwd = 1, col = "black")
  segments(22.1,2.3, 22.1,-3.4,
           lwd = 1, col = "black")
  segments(24.4,2.3, 24.4,-3.4,
           lwd = 1, col = "black")
  segments(28,2.3, 28,-3.4,
           lwd = 1, col = "black")
  segments(30.3,2.3, 30.3,-3.4,
           lwd = 1, col = "black")
  segments(9,14.2, 9,9.7,
           lwd = 1, col = "black")
  segments(11.5,14.2, 11.5,9.7,
           lwd = 1, col = "black")
  segments(13.8,14.2, 13.8,9.7, 
           lwd = 1, col = "black")
  segments(16.2,14.2, 16.2,9.7,
           lwd = 1, col = "black")
  segments(13.8,14.2, 13.8,9.7, 
           lwd = 1, col = "black")
  segments(19.7,14.2, 19.7,9.7,
           lwd = 1, col = "black")
  segments(22.1,14.2, 22.1,9.7,
           lwd = 1, col = "black")
  segments(25.6,14.2, 25.6,9.7,
           lwd = 1, col = "black")
  segments(28.1,14.2, 28.1,9.7,
           lwd = 1, col = "black")
  segments(30.5,14.2, 30.5,9.7,
           lwd = 1, col = "black")
  segments(3,9.7, 33.8,9.7,
           lwd = 1, col = "black")
  segments(3,14.2, 33.8,14.2,
           lwd = 1, col = "black")
  segments(3,2.3, 33.8,2.3,
           lwd = 1, col = "black")
  segments(3,-3.4, 33.8,-3.4,
           lwd = 1, col = "black")
  segments(3,2.3, 3,-3.4,
           lwd = 1, col = "black")
  segments(3,9.7, 3,14.2,
           lwd = 1, col = "black")
  segments(33.8,-3.4, 33.8,14.2,
           lwd = 1, col = "black")
  polygon(x = c(3, 3, 7.9, 7.9),  
        y = c(4, 6.4, 6.4, 4),    
        border = "black",             
        lwd = 1)                   
  polygon(x = c(14, 14, 19.9, 19.9),  
        y = c(4, 6.4, 6.4, 4),    
        border = "black",             
        lwd = 1)                   
  polygon(x = c(27, 27, 31, 31),  
        y = c(4, 6.4, 6.4, 4),    
        border = "black",             
        lwd = 1)                   
  segments(-0.5,-1.2, -0.5,14.2,
           lwd = 1, col = "black")
  segments(-0.5,-1.2, 3, -1.2,
           lwd = 1, col = "black")
  segments(-0.5,14.2, 3,14.2,
           lwd = 1, col = "black")
}


floorErrorMap(test_data.final[1:2], test_data.final[4:5], AP = Access.Points[2:3])
```



```{r}
test_data.final[30,]


floorErrorMap(test_data.final[30, 1:2], test_data.final[30, 4:5], AP = Access.Points[2:3])

test_data.m.t.pred %>%
  filter(
    Scan.pos.x == test_data.final[30,1],
    Scan.pos.y == test_data.final[30,2],
    orientation.r == test_data.final[30,3]
  ) %>%
  `[`(c(6,7,10)) %>% as.matrix() %>%
  apply(1, function(x) {
    plotrix::draw.circle(x["AP.pos.x"], x["AP.pos.y"], x["pred_dist"])
  })



floorErrorMap(test_data.final[30, 1:2], test_data.final[30, 4:5], AP = Access.Points[2:3])
test_data.m.t.pred %>%
  filter(
    Scan.pos.x == test_data.final[30,1],
    Scan.pos.y == test_data.final[30,2],
    orientation.r == test_data.final[30,3]
  ) %>%
  `[`(c(6,7,5)) %>% as.matrix() %>%
  apply(1, function(x) {
    plotrix::draw.circle(x["AP.pos.x"], x["AP.pos.y"], x["distance"])
  })
```

```{r}
test_data.m.t.pred %>%
  mutate(`Distance Error` = abs(pred_dist - distance)) %>%
  ggplot(aes(x = `Distance Error` , fill = MAC)) +
  geom_histogram(binwidth = 1) + 
  facet_wrap(.~MAC) + 
  theme(legend.position = "None")
```



```{r}
median(test_data.final$err)
mean(test_data.final$err)
```

