---
title: "Offline Distances"
author: "Cyrus Cravens"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tinytex)   # Helper Functions to Install and Maintain TeX Live, and Compile LaTeX Documents
library(rlang)     # Functions for Base Types and Core R and 'Tidyverse' Features
library(rmarkdown) # Dynamic Documents for R
library(knitr)
library(tidyverse) # Load core packages:
library(ggplot2)   # data visualization.
library(dplyr)     # data manipulation.
library(tidyr)     # data tidying.
library(readr)     # data import.
library(purrr)     # functional programming.
library(tibble)    # tibbles, a modern re-imagining of data frames.
library(stringr)   # strings.
library(forcats)   # factors.
library(lubridate) # date/times.
library(readr)     # reading .csv, .tsv, and .fwf files.
library(readxl)    # reading .xls, and .xlxs files.
library(feather)   # sharing with Python and other languages.
library(haven)     # SPSS, SAS and Stata files.
library(httr)      # web apis.
library(jsonlite)   # JSON.
library(rvest)     # web scraping.
library(xml2)      # XML.
library(modelr)    # modelling within a pipeline
library(broom)     # turning models into tidy data
library(hms)       # times.
library(magrittr)  # Pipeline operator
library(lobstr)    # Visualizing abstract syntax trees, stack trees, and object sizes
library(pander)    # Exporting/converting complex pandoc documents, EX: df to Pandoc table
library(ggforce)   # More plot functions on top of ggplot2
library(ggpubr)    # Automatically add p-values and significance levels  plots.
library(sf)        # Geo-spatial vector manipulation: points, lines, polygons
library(ff)
library(ldat)
library(rio)
library(jsonlite)
library(reader)
library(qdapRegex)
library(sp)
```

```{r}
# Set working directory as needed
#setwd("")
```

# Import CSV files

```{r}
#import offline data
offline <- read_csv("tidy_data/tidy_offline.csv")
summary(offline)
```

```{r}
#Import online data
online <- read_csv("tidy_data/tidy_online.csv")
summary(online)
```
## Applying Pythagorean Theorem To `Offline` data

```{r}
# I am creating new variables to apply Pythagorean theorem to plot radius 
offline <- mutate(offline, a = (abs(posX-ap_x))) %>%  # creates distance between x coordinates 
  mutate(offline, b = (abs(posY-ap_y))) %>% # creates distance between y coordinates 
  mutate(offline, c = (sqrt(a^2+b^2))) # finds distance between (x,y) points
offline
```

## Distinct Online Receiver Locations 

```{r}
# finds distinct points to plot for data visualization of online recorded points 
on_rec_locs <- online %>% 
  select(receiver, posX, posY) %>% 
  distinct()
#rec_locs[, 2:3] <- sapply(rec_locs[, 2:3], as.geom)
on_rec_locs
plot(on_rec_locs$posX, on_rec_locs$posY) # checking plot locations
```

## Distinct Offline Receiver Locations 

```{r}
# finds distinct points to plot for data visualization of offline recorded points 
off_rec_locs <- offline %>% 
  select(receiver, posX, posY) %>% 
  distinct()
#rec_locs[, 2:3] <- sapply(rec_locs[, 2:3], as.geom)
off_rec_locs
plot(off_rec_locs$posX, off_rec_locs$posY) # checking plot locations
```

## Access Point Locations
```{r}
# finds distinct points to plot for data visualization of access point locations 
ap_locs <- offline %>% 
  select(c("ap_mac", "ap_x", "ap_y")) %>% 
  distinct() %>%  # trimming excess access point locations 
  na.omit()  # removing na values
ap_locs
# checking results
plot(ap_locs$"ap_x", ap_locs$"ap_y") # plotting access point locations
```

### Access Points Min/Max Distances
```{r}
# select(offline, orientation) %>% distinct()
```



```{r}
ap_locs # checking access point locations df
c_max <- setNames(aggregate(new_off$c, by = list(new_off$ap_mac), max), c("ap_mac", "max_dist")) # finding max distance per access point
c_min <- setNames(aggregate(new_off$c, by = list(new_off$ap_mac), min), c("ap_mac", "min_dist")) # finding the minimum distance from access point to offline (x,y) coordinate
ap_dist <- merge(ap_locs, c_max, by="ap_mac") # combining c_max df to ap_dist df
ap_dist <- merge(ap_dist, c_min, by="ap_mac") # combining c_min df to ap_dist df
ap_dist
```

## Creating Floorplan
```{r}
#MULTILINESTRING
outer <- rbind(c(-0.5,-1.2), c(-0.5,14.2), c(33.8,14.2), c(33.8,-3.4), c(3,-3.4), c(3,-1.2),c(-0.5,-1.2)) #creating exterior outline
low_rms <- rbind(c(3,-1.2), c(3,2.3), c(33.8,2.3))  #creating lower room outline
# Creating lower section separating walls
lw1 <- rbind(c(7.8,2.3), c(7.8,-3.4))
lw2 <- rbind(c(11.3,2.3), c(11.3,-3.4))
lw3 <- rbind(c(16.1,2.3), c(16.1,-3.4))
lw4 <- rbind(c(19.8,2.3), c(19.8,-3.4))
lw5 <- rbind(c(22.1,2.3), c(22.1,-3.4))
lw6 <- rbind(c(24.4,2.3), c(24.4,-3.4))
lw7 <- rbind(c(28,2.3), c(28,-3.4))
lw8 <- rbind(c(30.3,2.3), c(30.3,-3.4))
up_rms <- rbind(c(3,14.2), c(3,9.7), c(33.8,9.7)) #creating upper room outline
# Creating lower section separating walls
uw1 <- rbind(c(9,14.2), c(9,9.7))
uw2 <- rbind(c(11.5,14.2), c(11.5,9.7))
uw3 <- rbind(c(13.8,14.2), c(13.8,9.7))
uw4 <- rbind(c(16.2,14.2), c(16.2,9.7))
uw5 <- rbind(c(19.7,14.2), c(19.7,9.7))
uw6 <- rbind(c(22.1,14.2), c(22.1,9.7))
uw7 <- rbind(c(25.6,14.2), c(25.6,9.7))
uw8 <- rbind(c(28.1,14.2), c(28.1,9.7))
uw9 <- rbind(c(30.5,14.2), c(30.5,9.7))

#creating multilinestring library(sf)
(mls <- st_multilinestring(list(outer,low_rms,lw1,lw2,lw3,lw4,lw5,lw6,lw7,lw8,up_rms,uw1,uw2,uw3,uw4,uw5,uw6,uw7,uw8,uw9)))

plot(mls) # inspecting mls

#MULTIPOLYGON
#center-row LEFT room
p1 <- rbind(c(3,4), c(3,6.7), c(7.9,6.7), c(7.9,4), c(3,4))
#p2 <- rbind(c(3.2,4.2), c(3.2,6.5), c(7.7,6.5), c(7.7,4.2), c(3.2,4.2))
#pol <-st_polygon(list(p1,p2))
#center-row MIDDLE room
p3 <- rbind(c(13.6,4), c(13.6,6.7), c(19.9,6.7), c(19.9,4), c(13.6,4))
#p4 <- rbind(c(13.8,4.2), c(13.8,6.5), c(19.7,6.5), c(19.7,4.2), c(13.8,4.2))
#center-row RIGHT room
p5 <- rbind(c(27,4), c(27,6.7), c(31,6.7), c(31,4), c(27,4))
#p6 <- rbind(c(27.2,4.2), c(27.2,6.5), c(30.8,6.5), c(30.8,4.2), c(27.2,4.2))
#Creating multiple polygons library(sf)
(mpol <- st_multipolygon(list(list(p1), list(p3), list(p5))))

plot(mpol) # inspecting polygon
```

## Plot Combined base florplan
```{r}
base_grid <- ggplot() +
  # inserting floor plan outline
  geom_sf(data = mls) + 
  # inserting room polygons
  geom_sf(data = mpol) +
  # inserting ap locations
  geom_point(data = ap_locs, aes(ap_x, ap_y, colour=ap_mac),

             shape = 15,
             size = 1.5,
             show.legend = NA)+
  # inserting offline receiver locations
  geom_point(data = off_rec_locs, mapping = aes(posX,posY),
             colour = "grey",
             alpha = .8,
             size = 1)+
  # inserting online receiver locations
  geom_point(data = on_rec_locs, aes(posX,posY),
             color = "blue",
             alpha = .3,
             size = 1) +
  labs(
    title = "Base Floorplan",
    subtitle = "Grey dots are offline recorded positions whereas blue represents the online",
    # caption = "",
    # tag = "",
    x = "Roughly 35 meters",
    y = "Roughly 18 meters",
    # colour = ""
  )
base_grid
```

```{r}
baseFloorplan <- print(base_grid + labs(colour = "Acess Points"))
```
## Linear model to establish significance of variables

```{r}
new_off <- offline[-c(3,9,10,13,14)]
view(new_off)
```

```{r}
off_xy <- new_off %>% select(posX, posY) %>% unique()
off_xy
```


```{r}
# Setting rssi as the dependent variable because it is what varies given proximity
rssi_lm <- lm(rssi~posX+posY+orientation+ap_x+ap_y, new_off) # this model excludes the c variable that is distance between receiver and ap
summary(rssi_lm) # note: orientation has a p value of 0.432 making it insignificant
```

```{r}
# Setting rssi as the dependent variable because it is what varies given proximity 
rssi_lm2 <- lm(rssi~posX+posY+orientation+ap_x+ap_y+c, new_off) # this model includes c variable to examine what happens to the p-value for orientation
summary(rssi_lm2) # note that the p value for orientation has gotten larger by 20.7% making it non-significant to rssi values that determine signal strength
```

```{r}
fortify(rssi_lm2)
```

### Ploting timeline values

```{r}
# uniq_xy <- 
  new_off %>% select(posX, posY) %>% distinct()
# uniq_xy
```

```{r}
new_split <- new_off %>% group_split(posX, posY) # breaking up dataframe so it's easier to plot.
new_split[1] # format to call split df when plotting
```


```{r}
# baseFloorplan + geom_circle(aes(x0=ap_x, y0=ap_y, r=c), data = offline)
```


